name: 'Windows Build'

description: |
  Build the project on Windows.
  From Summer 2025, this is not maintained, and we rely instead
  on python wheels biult by cibuildwheel.

inputs:
  compiler-version:
    default: 12
  python-version:
    required: false
    default: '3.13'

runs:
    using: "composite"
    steps:
      - name: Setup Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          architecture: 'x64'

      - name: Install prerequisites
        shell: bash
        run: |
          pip3 install -r requirements-build.txt
      - name: Run conan
        shell: bash
        run: |
          conan profile detect --force
          conan profile show
          conan install . --output-folder=build --build=missing --profile:build=conan2/windows-profile --profile:host=conan2/windows-profile
      - name: Configure and build
        shell: bash
        run: |
           cd build/
           cmake .. -DCMAKE_TOOLCHAIN_FILE=build/Release/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release
           cmake --build .

      - name: Archive Python Application
        uses: actions/upload-artifact@v4
        with:
          name: CosmoSimPy-windows-python${{ inputs.python-version }}
          path: build/lib/CosmoSimPy.*.pyd
      - name: Test
        shell: bash
        run: |
          pip3 install -r requirements.txt
          cp build/lib/CosmoSimPy.*.pyd CosmoSimPy/CosmoSim
          python3 CosmoSimPy/datagen.py
