# (C) 2023: Hans Georg Schaathun <georg@schaathun.net> 

name: "Regression Test on Windows"

description: |
  Run regression tests specifically on windows.
  As of August 2025, this does not work.

on: 
   push:
       branches: [ feature/regressiontests ]
   release:
   workflow_dispatch:
   workflow_call:

jobs:

  build-on-windows:
    name: Build on Windows
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        compiler-version: [10]
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4
      - name: Build Project
        uses: ./.github/actions/build-windows
        with:
           compiler-version: ${{ matrix.compiler-version }}
           python-version: ${{ matrix.python-version }}

  regression-test:

    runs-on:  ${{ matrix.os }}
    needs: 
      - build-on-windows
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        test-dir: [ 'exactpm', 'raytrace', 'roulette', 'roulettepm',
          'new-roulette', 'new-raytrace',
          'sampled-roulette', 'sampled-raytrace',
          'cluster-roulette', 'cluster-raytrace',
          'cluster-sampled-roulette', 'cluster-sampled-raytrace',
        ]
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
          cache: "pip"
      - name: pip-installations
        run: |
          pip install -r requirements.txt
      - name: artifact
        uses: actions/download-artifact@v4
        with:
          path: .
      - name: diagnostic
        shell: bash
        run: |
            git status
            python3 --version
            ls -l
      - name: move artifacts in place
        shell: bash
        run: |
          mv CosmoSimPy-*-python*/CosmoSimPy.*.pyd  CosmoSimPy/CosmoSim
      - name: makeimages
        run: |
          cd RegressionTest/${{ matrix.test-dir }}
          sh ../bin/makeimages.sh
      - name: compare
        run: |
          cd RegressionTest/${{ matrix.test-dir }}
          sh ../bin/compareimages.sh
      - name: montage
        run: |
          cd RegressionTest/${{ matrix.test-dir }}
          sh ../bin/montageimages.sh
      - name: artifact-preparation
        run: |
          mkdir -p dist/${{ matrix.os }}/python${{ matrix.python-version }}/${{ matrix.test-dir }}
          mv RegressionTest/${{ matrix.test-dir }}/montage/ dist/${{ matrix.os }}/python${{ matrix.python-version }}/${{ matrix.test-dir }}
      - name: image-upload
        uses: actions/upload-artifact@v4
        with:
          name: montage-${{ matrix.os }}-${{ matrix.test-dir }}
          path: dist


