# (C) 2024: Hans Georg Schaathun <georg@schaathun.net> 

name: Make Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  build:
    uses: ./.github/workflows/dist.yml


  release:
    permissions: write-all
    name: Release and Upload Assets
    runs-on: ubuntu-latest
    strategy:
       fail-fast: false

    needs:
      - build

    steps:
      - uses: actions/checkout@v4
      - name: Download a all artifact
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Display artifacts
        run: ls -lR
        working-directory: dist
      - name: PKZip the asset
        run: |
          zip -r CosmoSimPy.zip CosmoSimPy
          zip -r CosmoGUI-application-macos-12.zip CosmoGUI-app*-12
          zip -r CosmoGUI-application-macos-14.zip CosmoGUI-app*-14
        working-directory: dist

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          files: |
             dist/CosmoSimPy.zip
             dist/CosmoGUI-application-macos-12.zip
             dist/CosmoGUI-application-macos-14.zip
