name: 'Macos Build'

description: Build the project on Macos

inputs:
  compiler-version:
    default: 14
  python-version:
    required: false
    default: '3.10'

runs:
    using: "composite"

    steps:
      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          architecture: 'x64'

      - name: Install prerequisites
        shell: bash
        run: |
          sudo pip3 install conan==1.64
          conan profile new default --detect
          conan profile update settings.compiler.version=${{ inputs.compiler-version }} default

          ###       - name: Config Conan
          ###         shell: bash
          ###         run: |
          ###           conan profile new default --detect
          ###           conan profile update settings.compiler.libcxx=libstdc++ default
          ###           # Not that this setting is different from what we use on linux and windows
      - name: Run conan
        shell: bash
        run: |
          conan install . -s build_type=Release -if build -b missing
      - name: Configure and build
        shell: bash
        run: |
          cmake . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
      - name: Make Python Distribution
        shell: bash
        run: |
           mkdir -p dist/CosmoSimPy/CosmoSim
           cp build/lib/CosmoSimPy.*.so dist/CosmoSimPy/CosmoSim/
      - name: Archive Python link library
        uses: actions/upload-artifact@v3
        with:
          name: python-link-library
          path: build/lib/CosmoSimPy.*.so
      - name: Archive Python Application
        uses: actions/upload-artifact@v3
        with:
          name: CosmoSimPy
          path: dist
      - name: Test
        shell: bash
        run: |
          pip3 install -r requirements.txt
          cp build/lib/CosmoSimPy.*.so CosmoSimPy/CosmoSim
          python3 CosmoSimPy/datagen.py
