name: 'Macos Build'

description: |
  Build the project locally on MacOS.  Not maintained from Summer'25.
  Build wheels for PyPI/pip instead.

inputs:
  compiler-version:
    default: 14
  python-version:
    required: false
    default: '3.10'

runs:
    using: "composite"
    steps:
      - name: Setup Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          architecture: 'x64'

      - name: Install prerequisites
        shell: bash
        run: |
          pip3 install -r requirements-build.txt
          conan profile detect 
          conan profile show
          # conan profile update settings.compiler.version=${{ inputs.compiler-version }} default
      - name: Run conan
        shell: bash
        run: |
          conan install . --output-folder=build --build=missing 
      - name: Configure and build
        shell: bash
        run: |
           cd build 
           cmake .. -DCMAKE_TOOLCHAIN_FILE=build/Release/generators/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release && \
           cmake --build . 
           cmake --install . --prefix=../src
      - uses: kenchan0130/actions-system-info@master
        id: system-info
      - name: Archive Python link library
        uses: actions/upload-artifact@v4
        with:
          name: CosmoSimPy-macos-${{ steps.system-info.outputs.release }}-python${{ inputs.python-version }}
          path: src/CosmoSim/CosmoSimPy.*.so
      - name: Test
        shell: bash
        run: |
          ls -l src/CosmoSim
          date
          python3 --version
          PYTHONPATH=src/:$PYTHONPATH python3 -m CosmoSim.datagen
