
name: MacOS-arm64

on: [workflow_dispatch]

jobs:

  conan-on-darwin-arm64:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11]
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
  
      - name: Install prerequisites
        run: |
          pip3 install conan==1.59
          pip3 install pyinstaller
      - name: Run conan
        run: |
          conan install . -s build_type=Release -if build -b missing
      - name: Configure and build
        run: |
          cmake . -B build -DCMAKE_BUILD_TYPE=Release -DCROSS_COMPILE="-target arm64-apple-macos11" --log-level=DEBUG
          cmake --build build --log-level=DEBUG
      - name: Make application bundle
        run: |
          pyinstaller --windowed --osx-bundle-identifier no.ntnu.iir.CosmoGUI Python/CosmoGUI.py
      - name: Archive Python link library
        uses: actions/upload-artifact@v3
        with:
          name: CosmoSimPy-library-${{matrix.os}}-arm64
          path: build/lib/CosmoSimPy.*
      - name: Remove non-app data
        run: |
          rm -rf dist/CosmoGUI
      - name: Archive Python link library
        uses: actions/upload-artifact@v3
        with:
          name: CosmoGUI-application-${{matrix.os}}-arm64
          path: dist

