# (C) 2023: Hans Georg Schaathun <georg@schaathun.net> 

name: MacOS

on: 
   release:
   workflow_dispatch:
   push:
     branches: [develop]

jobs:

  build:

    runs-on: ${{ matrix.os }}
    env:
      CC: gcc-${{ matrix.compiler_version }}
      CXX: g++-${{ matrix.compiler_version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-14]
        compiler_version: [10,14]
        python_version: ['3.11', '3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Build Project
        uses: ./.github/actions/build-darwin
        with:
           compiler_version: ${{ matrix.compiler_version }}
           python_version: ${{ matrix.python_version }}


  app:

    runs-on: ${{ matrix.os }}
    env:
      CC: gcc-${{ matrix.compiler_version }}
      CXX: g++-${{ matrix.compiler_version }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12, macos-14]
        compiler_version: [10,14]
        python_version: ['3.11']
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python_version: ${{ matrix.python_version }}
          architecture: 'x64'
  
      - name: Install prerequisites
        run: |
          pip3 install conan==1.60
          pip3 install pyinstaller
      - name: Run conan
        run: |
          conan install . -s build_type=Release -if build -b missing
      - name: Configure and build
        run: |
          cmake . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
      - name: Make application bundle
        run: |
          pyinstaller --windowed --osx-bundle-identifier no.ntnu.iir.CosmoGUI CosmoSimPy/CosmoGUI.py
      - name: Remove non-app data
        run: |
          rm -rf dist/CosmoGUI
      - name: Archive Python link library
        uses: actions/upload-artifact@v3
        with:
          name: CosmoGUI-application-${{matrix.os}}
          path: dist
