# (C) 2023: Hans Georg Schaathun <georg@schaathun.net> 

name: MacOS

on: [release, workflow_dispatch]

jobs:

  conan-on-darwin:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11]
        python-version: ['3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Build Project
        uses: ./.github/actions/build-darwin
        with:
           compiler-version: ${{ matrix.compiler-version }}
           python-version: ${{ matrix.python-version }}


  macos-app:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11]
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
  
      - name: Install prerequisites
        run: |
          pip3 install conan==1.59
          pip3 install pyinstaller
      - name: Run conan
        run: |
          conan install . -s build_type=Release -if build -b missing
      - name: Configure and build
        run: |
          cmake . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
      - name: Make application bundle
        run: |
          pyinstaller --windowed --osx-bundle-identifier no.ntnu.iir.CosmoGUI CosmoSimPy/CosmoGUI.py
      - name: Remove non-app data
        run: |
          rm -rf dist/CosmoGUI
      - name: Archive Python link library
        uses: actions/upload-artifact@v3
        with:
          name: CosmoGUI-application-${{matrix.os}}
          path: dist
