# (C) 2023: Hans Georg Schaathun <georg@schaathun.net> 

name: Debugging MacOS

on:
  workflow_dispatch:
  push:
     branches: [workflow-debug,develop]

jobs:

  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14]
        compiler-version: [ '15.0' ]
        python-version: ['3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Build Project
        uses: ./.github/actions/build-darwin
        with:
           python-version: ${{ matrix.python-version }}
           compiler-version: ${{ matrix.compiler-version }}


  app:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14]
        python-version: ['3.12']
        compiler-version: [ '15.0' ]

    steps:
      - uses: actions/checkout@v4
      - name: Build Project
        uses: ./.github/actions/macos-app
        with:
           python-version: ${{ matrix.python-version }}
           compiler-version: ${{ matrix.compiler-version }}
