# (C) 2024: Hans Georg Schaathun <georg@schaathun.net> 

name: Test dist

on:
   push:
     branches: [ test-dist ]
   workflow_dispatch:
   workflow_call:

jobs:

  build:
    uses: ./.github/workflows/build-production.yml

  python-dist:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs: build

    steps:
      - uses: actions/checkout@v4
      - name: Download a all artifact
        uses: actions/download-artifact@v4
        with:
          path: dist-tmp
      - name: Display artifacts
        run: ls -lR
        working-directory: dist-tmp
      - name: Make Python Distribution
        run: |
           mkdir -p dist/CosmoSimPy/CosmoSim
           rsync -av CosmoSimPy/ dist/CosmoSimPy/
           mv dist-tmp/CosmoSimPy*/*.* dist/CosmoSimPy/CosmoSim
      - name: Archive Python Application
        uses: actions/upload-artifact@v4
        with:
          name: CosmoSimPy
          path: dist

