# (C) 2023: Hans Georg Schaathun <georg@schaathun.net> 

name: Test dist

on:
   push:
     branches: [ upgrade-uploader ]
   workflow_dispatch:

jobs:

  build:
    uses: ./.github/workflows/build-production.yml

  python-dist:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Download a all artifact
        uses: actions/download-artifact@v3
        with:
          path: dist-tmp
      - name: Make Python Distribution
        run: |
           mkdir -p dist/CosmoSimPy/CosmoSim
           rsync -av CosmoSimPy/ dist/CosmoSimPy/
           mv dist-tmp/*.so dist-tmp/*.pyd dist/CosmoSimPy/CosmoSim
      - name: Archive Python Application
        uses: actions/upload-artifact@v4
        with:
          name: CosmoSimPy
          path: dist

