
name: Debugging for Python 3.12

on: 
   push:
       branches:  [ python312 ]
   workflow_dispatch:
   workflow_call:

jobs:


  windows:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ['3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Build Project
        uses: ./.github/actions/build-windows
        with:
           compiler-version: ${{ matrix.compiler-version }}
           python-version: ${{ matrix.python-version }}


  macos-12:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12]
        compiler-version: [ 14 ]
        python-version: [ '3.12' ]
    steps:
      - uses: actions/checkout@v4
      - name: Build Project
        uses: ./.github/actions/build-darwin
        with:
           python-version: ${{ matrix.python-version }}
           compiler-version: ${{ matrix.compiler-version }}

  macos:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14]
        compiler-version: [ '15.0' ]
        python-version: [ '3.12' ]
    steps:
      - uses: actions/checkout@v4
      - name: Build Project
        uses: ./.github/actions/build-darwin
        with:
           python-version: ${{ matrix.python-version }}
           compiler-version: ${{ matrix.compiler-version }}

