# (C) 2023: Hans Georg Schaathun <georg@schaathun.net> 

name: "Regression Test (Modular)"

on: 
   push:
       branches: [ refactor/test-suites ]
       tags: 'v*' 
   workflow_dispatch:
   workflow_call:

jobs:
  build-on-linux:

    name: Build on Linux
    runs-on: ${{ matrix.os }}
    env:
      CC: gcc-${{ matrix.compiler-version }}
      CXX: g++-${{ matrix.compiler-version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        compiler-version: [10]
        python-version: ['3.11']

    steps:
      - uses: actions/checkout@v3
      - name: Build Project
        uses: ./.github/actions/build-linux
        with:
           compiler-version: ${{ matrix.compiler-version }}
           python-version: ${{ matrix.python-version }}

  build-on-windows:
    name: Build on Windows
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019]
        compiler-version: [10]
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Build Project
        uses: ./.github/actions/build-windows
        with:
           compiler-version: ${{ matrix.compiler-version }}
           python-version: ${{ matrix.python-version }}

  regressiion-test:

    runs-on:  ${{ matrix.os }}
    needs: 
      - build-on-windows
      - build-on-linux
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04,windows-2019]
        test-dir: [ 'exactpm', 'raytrace', 'rotatedsis', 'roulette', 'roulettepm' ]
    steps:
      - uses: actions/checkout@v3
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: CosmoSimPy
          path: .
      - name: diagnostic
        run: |
          git status
          ls -lR CosmoSimPy
      - name: makeimages
        run: |
          cd RegressionTest/${{ matrix.test-dir }}
          make images.status
      - name: compare
        run: |
          cd RegressionTest/${{ matrix.test-dir }}
          make compare.status
      - name: montage
        run: |
          cd RegressionTest/${{ matrix.test-dir }}
          make montage.status
      - name: image-upload
        uses: actions/upload-artifact@v3
        with:
          name: montage-
          path: |
              RegressionTest/*/montage*
              RegressionTest/*/*.log/



