# (C) 2025: Hans Georg Schaathun <georg@schaathun.net> 

name: Release on github

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Project
        uses: ./.github/actions/build

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  release:
    permissions: write-all
    name: Release and Upload Assets
    runs-on: ubuntu-latest
    strategy:
       fail-fast: false

    needs:
      - build_sdist

    steps:
      - uses: actions/checkout@v4
      - name: Download a all artifact
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Display artifacts
        run: ls -lR
        working-directory: dist
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          files: |
             dist/*.tar.gz
             dist/*.zip
