# (C) 2024: Hans Georg Schaathun <georg@schaathun.net> 

name: Make Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  build:
    uses: ./.github/workflows/trial-run.yml

  python-dist:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      - name: Make Python Distribution
        run: |
           mkdir -p dist/CosmoSimPy
           rsync -av CosmoSimPy/ dist/CosmoSimPy/
      - name: Archive Python Application
        uses: actions/upload-artifact@v3
        with:
          name: CosmoSimPy
          path: dist

  release:
    permissions: write-all
    name: Upload Release Asset
    runs-on: ubuntu-latest
    strategy:
       fail-fast: false

    needs:
      - build
      - python-dist

    steps:
      - uses: actions/checkout@v3
      - name: Download a all artifact
        uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Display artifacts
        run: ls -lR
        working-diretory: dist
      - name: PKZip the asset
        run: |
          zip -r CosmoSimPy.zip CosmoSimPy
          zip -r CosmoGUI-application-macos-12.zip CosmoGUI-application-macos-12
          zip -r CosmoGUI-application-macos-14.zip CosmoGUI-application-macos-14
        working-diretory: dist
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-lib
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./dist/CosmoSimPy.zip
          asset_name: CosmoSimPy.zip
          asset_content_type: application/zip
      - name: Upload Release Asset
        id: upload-app-12
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./dist/CosmoGUI-application-macos-12.zip
          asset_name: CosmoSimPy.zip
          asset_content_type: application/zip
      - name: Upload Release Asset
        id: upload-app-14
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: ./dist/CosmoGUI-application-macos-14.zip
          asset_name: CosmoSimPy.zip
          asset_content_type: application/zip
