# (C) 2024: Hans Georg Schaathun <georg@schaathun.net> 

name: Test Release

on:
   push:
     # branches: [ upgrade-uploader ]
     tag: 
       - 'test-release*'
   workflow_dispatch:

jobs:

  build:
    uses: ./.github/workflows/dist.yml

  release:
    permissions: write-all
    name: Release and Upload Assets
    runs-on: ubuntu-latest
    strategy:
       fail-fast: false

    needs:
      - build

    steps:
      - uses: actions/checkout@v4
      - name: Download a all artifact
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Display artifacts
        run: ls -lR
        working-directory: dist
      - name: PKZip the asset
        run: |
          zip -r CosmoSimPy.zip CosmoSimPy
        working-directory: dist

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
             dist/CosmoSimPy.zip
