
name: Test Composite Action

on:
   push:
     branches: []
   workflow_dispatch:

jobs:
  build:
    name: Test composite action
    runs-on: ubuntu-latest
    env:
      CC: gcc-10 # ${{ compiler-version }}
      CXX: g++-10 # ${{ compiler-version }}
    steps:
      - uses: actions/checkout@v3
      - name: Build Project
        uses: ./.github/actions/build-linux
