
name: Stable Trial Build

on: 
   push:
     branches: [main, master, develop, workflow-debug]
   workflow_dispatch:
   workflow_call:

jobs:
  linux:

    runs-on: ${{ matrix.os }}
    env:
      CC: gcc-${{ matrix.compiler_version }}
      CXX: g++-${{ matrix.compiler_version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        compiler_version: [10]
        python-version: ['3.10','3.11','3.12']

    steps:
      - uses: actions/checkout@v3
      - name: Build Project
        uses: ./.github/actions/build-linux
        with:
           compiler-version: ${{ matrix.compiler-version }}
           python-version: ${{ matrix.python-version }}

  windows:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        python-version: ['3.10','3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Build Project
        uses: ./.github/actions/build-windows
        with:
           compiler-version: ${{ matrix.compiler-version }}
           python-version: ${{ matrix.python-version }}


  macos:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12 ]
        compiler-version: [ 14 ]
        python-version: ['3.11', '3.10']
    steps:
      - uses: actions/checkout@v3
      - name: Build Project
        uses: ./.github/actions/build-darwin
        with:
           python-version: ${{ matrix.python-version }}
           compiler-version: ${{ matrix.compiler-version }}

  macos-14:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14]
        compiler-version: [ '15.0' ]
        python-version: [ '3.11' ]
    steps:
      - uses: actions/checkout@v3
      - name: Build Project
        uses: ./.github/actions/build-darwin
        with:
           python-version: ${{ matrix.python-version }}
           compiler-version: ${{ matrix.compiler-version }}

  app:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-12]
        python-version: ['3.11']
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'
  
      - name: Install prerequisites
        run: |
          pip3 install conan==1.60
          conan profile new default --detect
          conan profile update settings.compiler.version=14 default
          pip3 install pyinstaller
      - name: Run conan
        run: |
          conan install . -s build_type=Release -if build -b missing
      - name: Configure and build
        run: |
          cmake . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build
      - name: Make application bundle
        run: |
          pyinstaller --windowed --osx-bundle-identifier no.ntnu.iir.CosmoGUI CosmoSimPy/CosmoGUI.py
      - name: Remove non-app data
        run: |
          rm -rf dist/CosmoGUI
      - name: Archive Python link library
        uses: actions/upload-artifact@v3
        with:
          name: CosmoGUI-application-${{matrix.os}}
          path: dist
