# (C) 2025: Hans Georg Schaathun <hg@schaathun.net>

name: Trial Build

description: |
  Test the local build of the project (not building python wheels).

  As of July 2025 we are not able to build on Windows.
  The Windows trial build is moved to the Legacy directory.

on: 
   push:
     branches: [ develop, refactor/workflows ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.12','3.13']
        include:
          - os: ubuntu-latest
            compiler-version: 13
          - os: macos-13
            compiler-version: 14
          - os: macos-14
            compiler-version: 14
          - os: macos-15
            compiler-version: 14
    steps:
      - uses: actions/checkout@v4
      - name: Build Project
        uses: ./.github/actions/build
        with:
           compiler-version: ${{ matrix.compiler-version }}
           python-version: ${{ matrix.python-version }}

