
name: Trial Build

on: 
   push:
     branches: [main, master, develop, build/conan2]

jobs:
  linux:

    runs-on: ${{ matrix.os }}
    env:
      CC: gcc-${{ matrix.compiler_version }}
      CXX: g++-${{ matrix.compiler_version }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04,ubuntu-latest]
        python-version: ['3.11','3.12','3.13']
    steps:
      - uses: actions/checkout@v4
      - name: Build Project
        uses: ./.github/actions/build-linux
        with:
           python-version: ${{ matrix.python-version }}
