# (C) 2025: Hans Georg Schaathun <georg+professor@schaathun.net> 

name: cibuildwheel

description: |
  Build python wheels for deployment to the PyPI server.
  This is the most critical workflow in the project.
  As of August 2025 it works with the architectures present.

  Building on Windows is erratic.  It succeeded once on 4 Aug'25,
  but subsequent runs of the same version on the same day failed.

on: 
   push:
       branches: [ "develop", "build/pypi*", "refactor/workflow*" ]
   workflow_call:
   workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest ]
# os: [ubuntu-24.04-arm, windows-latest, windows-11-arm, macos-13]

    steps:
      - uses: actions/checkout@v4

      # Used to host cibuildwheel
      - uses: actions/setup-python@v5
        with:
           python-version: '3.13'

      - name: Upgrade pip
        run: |
           python --version
           python -m pip install --upgrade pip

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.1.2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse

      - uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

